"""Updating users table for TOTP setup

Revision ID: 0157205d4a2e
Revises: 0f3ae9fc03e3
Create Date: 2025-01-18 13:53:45.931732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0157205d4a2e'
down_revision: Union[str, None] = '0f3ae9fc03e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###
