"""Users Table Migration

Revision ID: 0f3ae9fc03e3
Revises: 1dca544a8766
Create Date: 2025-01-08 22:56:10.849442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3ae9fc03e3'
down_revision: Union[str, None] = '1dca544a8766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_type', sa.Enum('oidc', 'local'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_type')
    # ### end Alembic commands ###
