"""Users Table Migration

Revision ID: 0f3ae9fc03e3
Revises: 1dca544a8766
Create Date: 2025-01-08 22:56:10.849442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3ae9fc03e3'
down_revision: Union[str, None] = '1dca544a8766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    auth_type = sa.Enum('oidc', 'local', name='auth_type')
    auth_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column('auth_type', auth_type, nullable=False)
    )
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_type')

    auth_type = sa.Enum(name='auth_type')
    auth_type.drop(op.get_bind(), checkfirst=True)
# ### end Alembic commands ###
