"""Converting last_used_otp to string

Revision ID: 103c5bb766a1
Revises: 18d14440c61c
Create Date: 2025-01-29 04:02:10.470503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '103c5bb766a1'
down_revision: Union[str, None] = '18d14440c61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_used_otp',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_used_otp',
               existing_type=sa.String(length=8),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
