"""new table to handle requests

Revision ID: 9dd6804d59a2
Revises: 3f15c1415342
Create Date: 2025-06-29 22:00:16.773093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd6804d59a2'
down_revision: Union[str, None] = '3f15c1415342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('request_title', sa.String(length=255), nullable=False),
    sa.Column('request_authors', sa.String(length=255), nullable=False),
    sa.Column('request_series', sa.String(length=255), nullable=True),
    sa.Column('request_seriesindex', sa.Float(), nullable=True),
    sa.Column('request_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_date', 'requests', ['request_date'], unique=False)
    op.create_index('ix_requests_id', 'requests', ['id'], unique=False)
    op.create_index('ix_requests_title_authors', 'requests', ['request_title', 'request_authors'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_title_authors', table_name='requests')
    op.drop_index('ix_requests_id', table_name='requests')
    op.drop_index('ix_requests_date', table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
